import { TaskType } from '../../features/tasks/ui/TasksList.tsx';

export const mockTasks: TaskType[] = [
  {
    id: '1',
    userId: '1',
    category: 'Default',
    title: 'my tasks 1',
    description:
      'aaaaaaaaaaaaaaf eeeeeeeeeeeeeeeeeeeeeeeee eeeeeeeeeeeeeeeeeeeeeeefef     eeeeeeeeee se fffffffffffffffffeeeeeeeeeeeeeeeeeeeeeeeeee',
    isCompleted: false,
    deadline: '05/12/25',
  },
  {
    id: '2',
    userId: '2',
    category: 'Default',
    title: 'my tasks 2',
    description: 'you',
    isCompleted: false,
    deadline: '05/12/25',
  },
  {
    id: '3',
    userId: '3',
    category: 'Default',
    title: 'my tasks 3',
    description: 'you',
    isCompleted: false,
    deadline: '05/12/25',
  },
  {
    id: '4',
    userId: '4',
    category: 'Default',
    title: 'my tasks 4',
    description: 'you',
    isCompleted: false,
    deadline: '05/12/25',
  },
  {
    id: '5',
    userId: '5',
    category: 'Default',
    title: 'my tasks 5',
    description: 'you',
    isCompleted: false,
    deadline: '05/12/25',
  },
  {
    id: '6',
    userId: '6',
    category: 'Default',
    title: 'my tasks 6',
    description: 'you',
    isCompleted: false,
    deadline: '05/12/25',
  },
  {
    id: '7',
    userId: '7',
    category: 'Default',
    title: 'my tasks 7',
    description: 'you',
    isCompleted: false,
    deadline: '05/12/25',
  },
  {
    id: '8',
    userId: '8',
    category: 'Default',
    title: 'my tasks 8',
    description: 'you',
    isCompleted: false,
    deadline: '05/12/25',
  },
];
